# Generated by Django 3.0.11 on 2021-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProdavnicaPloca', '0003_auto_20210214_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ploca',
            name='autor',
            field=models.CharField(max_length=200),
        ),
    ]
